var fullProductData = [
  // Model 1 (Basic Price £9,900)
  {
    "Basic Price": "£9,900",
    "Silage Price - Hyd Door Attach Style": "£11,493",
    "Silage Price - Swinging Door Style": "£12,000",
    "Body Size - Imperial": "12' x 7' 3\" - 7'6\" x 4'",
    "Standard Tyre Size": "12.5 x 15",
    Axle: "6 stud 70mm Single Axle",
    Brake: "300 x 60",
    "Carrying Capacity": "6.5 tons",
    "Floor Thickness": "5mm",
    "Side Thickness": "3.5mm",
    "Lights & Hyd Brakes": "Standard",
    "Side Loading Panels": "Standard",
    "Volume Basic": "360 cu.ft / 10.2 cu.mtrs",
    "Volume Silage - Swinging Door Style Sides": "720 cu.ft / 20.4 cu.mtrs",
    "Volume Silage - Hyd Door Attach. Style Sides": "N/A",
    "Basic Trailer Weight": "1680 kgs",
    "Loading Height Basic": '83"/2.11m',
    "Tip Angle (Degrees)": "50",
    "Tipping Height Basic": "N/A",

    "OPTIONAL EQUIPMENT - 400-60 x 15.5": "£420 / (DF-0.5)",
    "OPTIONAL EQUIPMENT - 340 x 65 x 18 Radial": "£998 / (DF-0.5)",
    "OPTIONAL EQUIPMENT - 550-45 x 22.5 c/w Mudguards": "N/A",
    "OPTIONAL EQUIPMENT - 560-45 x 22.5 c/w Mudguards": "N/A",
    "OPTIONAL EQUIPMENT - 560-60 x 22.5 c/w Mudguards": "N/A",
    "OPTIONAL EQUIPMENT - Mudguards / Wings - Bolt On": "N/A",
    "OPTIONAL EQUIPMENT - 8 inch Hatch": "£185",
    "OPTIONAL EQUIPMENT - 12 inch Hatch": "£228",
    "OPTIONAL EQUIPMENT - 12 inch Hatch with Sock": "£310",
    "OPTIONAL EQUIPMENT - Spring Drawbar (Adjustable)": "N/A",
    "OPTIONAL EQUIPMENT - Swivel Hitch": "N/A",
    "OPTIONAL EQUIPMENT - Hyd Door Safety Valve": "£215 / (DF-1.5)",
    "OPTIONAL EQUIPMENT - Hyd Door Seal": "£245",
    "OPTIONAL EQUIPMENT - Hyd Up & Over Grain Door": "£1,062",
    "OPTIONAL EQUIPMENT - Hydraulic Door Attachment Style Silage Sides":
      "Standard - When Hyd Grain Door & Silage Sides Specified",
    "OPTIONAL EQUIPMENT - Swinging Door Style Silage Sides":
      "Standard - When Hyd Grain Door Not Specified (DF-3)",
    "OPTIONAL EQUIPMENT - Trailer Cover (640g PVC)": "£227 / (DF-0.25)",
    "OPTIONAL EQUIPMENT - Roll Over Cover (1000g PVC)": "£1,588 / (DF-5)",
    "OPTIONAL EQUIPMENT - Hydraulic Front to Back Cover": "N/A",
    "OPTIONAL EQUIPMENT - LED Beacon": "£145 / (DF-0.25)",
    "OPTIONAL EQUIPMENT - LED Tail Lights": "Standard",
    "OPTIONAL EQUIPMENT - High Level LED Lights": "£292 / (DF-1.5)",
    "OPTIONAL EQUIPMENT - LED Worklights": "N/A",
    "OPTIONAL EQUIPMENT - 10 Stud 406 x 120 Commercial Axle": "N/A",
    "OPTIONAL EQUIPMENT - 10 Stud Commercial Axle c/w ABS & Air Brakes": "N/A",
    "OPTIONAL EQUIPMENT - Rear Steering Axle": "N/A",
    "OPTIONAL EQUIPMENT - Air / Oil Brakes (Non ABS)c/w Load Sensing": "N/A",
    "OPTIONAL EQUIPMENT - Oil Load Sensing": "N/A",
    "OPTIONAL EQUIPMENT - Small Perpsex Front Window": "£165 / (DF-0.5)",
    "OPTIONAL EQUIPMENT - Large Perspex Front Window": "N/A",
    "OPTIONAL EQUIPMENT - Rear Tow Hitch c/w Lights & Brakes": "N/A",
  },
  // Model 2 (Basic Price £13,200)
  {
    "Basic Price": "£13,200",
    "Silage Price - Hyd Door Attach Style": "£14,870",
    "Silage Price - Swinging Door Style": "£15,500",
    "Body Size - Imperial": "14' x 7' 3\" - 7'6\" x 4'",
    "Standard Tyre Size": "12.5 x 15",
    Axle: "6 stud 70mm",
    Brake: "300 x 60",
    "Carrying Capacity": "8.5 tons",
    "Floor Thickness": "5mm",
    "Side Thickness": "3.5mm",
    "Lights & Hyd Brakes": "Standard",
    "Side Loading Panels": "Standard",
    "Volume Basic": "420 cu.ft / 11.9 cu.mtrs",
    "Volume Silage - Swinging Door Style Sides": "840 cu.ft / 23.8 cu.mtrs",
    "Volume Silage - Hyd Door Attach. Style Sides": "710 cu.ft / 20.1 cu.mtrs",
    "Basic Trailer Weight": "2660 kgs",
    "Loading Height Basic": '89"/2.26m',
    "Tip Angle (Degrees)": "45",
    "Tipping Height Basic": "N/A",
    "OPTIONAL EQUIPMENT - 400-60 x 15.5": "£840 / (DF-1)",
    "OPTIONAL EQUIPMENT - 340 x 65 x 18 Radial": "£1996 / (DF-1)",
    "OPTIONAL EQUIPMENT - 550-45 x 22.5 c/w Mudguards": "N/A",
    "OPTIONAL EQUIPMENT - 560-45 x 22.5 c/w Mudguards": "N/A",
    "OPTIONAL EQUIPMENT - 560-60 x 22.5 c/w Mudguards": "N/A",
    "OPTIONAL EQUIPMENT - Mudguards / Wings - Bolt On": "£417",
    "OPTIONAL EQUIPMENT - 8 inch Hatch": "£185",
    "OPTIONAL EQUIPMENT - 12 inch Hatch": "£228",
    "OPTIONAL EQUIPMENT - 12 inch Hatch with Sock": "£310",
    "OPTIONAL EQUIPMENT - Spring Drawbar (Adjustable)": "£845",
    "OPTIONAL EQUIPMENT - Swivel Hitch": "N/A",
    "OPTIONAL EQUIPMENT - Hyd Door Safety Valve": "£215 / (DF-1.5)",
    "OPTIONAL EQUIPMENT - Hyd Door Seal": "£245",
    "OPTIONAL EQUIPMENT - Hyd Up & Over Grain Door": "£1,062",
    "OPTIONAL EQUIPMENT - Hydraulic Door Attachment Style Silage Sides":
      "Standard - When Hyd Grain Door & Silage Sides Specified",
    "OPTIONAL EQUIPMENT - Swinging Door Style Silage Sides":
      "Standard - When Hyd Grain Door Not Specified (DF-3)",
    "OPTIONAL EQUIPMENT - Trailer Cover (640g PVC)": "£227 / (DF-0.25)",
    "OPTIONAL EQUIPMENT - Roll Over Cover (1000g PVC)": "£1,588 / (DF-5)",
    "OPTIONAL EQUIPMENT - Hydraulic Front to Back Cover": "N/A",
    "OPTIONAL EQUIPMENT - LED Beacon": "£145 / (DF-0.25)",
    "OPTIONAL EQUIPMENT - LED Tail Lights": "Standard",
    "OPTIONAL EQUIPMENT - High Level LED Lights": "£292 / (DF-1.5)",
    "OPTIONAL EQUIPMENT - LED Worklights": "N/A",
    "OPTIONAL EQUIPMENT - 10 Stud 406 x 120 Commercial Axle": "N/A",
    "OPTIONAL EQUIPMENT - 10 Stud Commercial Axle c/w ABS & Air Brakes": "N/A",
    "OPTIONAL EQUIPMENT - Rear Steering Axle": "N/A",
    "OPTIONAL EQUIPMENT - Air / Oil Brakes (Non ABS)c/w Load Sensing":
      "£1,517 (DF-4)",
    "OPTIONAL EQUIPMENT - Oil Load Sensing": "£850 (DF-2)",
    "OPTIONAL EQUIPMENT - Small Perpsex Front Window": "£165 / (DF-0.5)",
    "OPTIONAL EQUIPMENT - Large Perspex Front Window": "N/A",
    "OPTIONAL EQUIPMENT - Rear Tow Hitch c/w Lights & Brakes": "£425 / (DF-2)",
  },
  // Model 3 (Basic Price £18,000)
  {
    "Basic Price": "£18,000",
    "Silage Price - Hyd Door Attach Style": "£20,129",
    "Silage Price - Swinging Door Style": "£21,200",
    "Body Size - Imperial": "16' x 7' 6\" - 8' x 4'",
    "Standard Tyre Size": "385 - 65 x 22.5",
    Axle: "8 stud 80mm",
    Brake: "350 x 90",
    "Carrying Capacity": "11 tons",
    "Floor Thickness": "5mm",
    "Side Thickness": "3.5mm",
    "Lights & Hyd Brakes": "Standard",
    "Side Loading Panels": "Standard",
    "Volume Basic": "496 cu.ft / 14.4 cu.mtrs",
    "Volume Silage - Swinging Door Style Sides": "992 cu.ft / 28.1 cu.mtrs",
    "Volume Silage - Hyd Door Attach. Style Sides": "889 cu.ft / 24.9 cu.mtrs",
    "Basic Trailer Weight": "4300 kgs",
    "Loading Height Basic": '95"/2.41m',
    "Tip Angle (Degrees)": "46",
    "Tipping Height Basic": "17' 8\"",
    "OPTIONAL EQUIPMENT - 400-60 x 15.5": "N/A",
    "OPTIONAL EQUIPMENT - 340 x 65 x 18 Radial": "N/A",
    "OPTIONAL EQUIPMENT - 550-45 x 22.5 c/w Mudguards": "£2,257",
    "OPTIONAL EQUIPMENT - 560-45 x 22.5 c/w Mudguards": "£2,947",
    "OPTIONAL EQUIPMENT - 560-60 x 22.5 c/w Mudguards": "N/A",
    "OPTIONAL EQUIPMENT - Mudguards / Wings - Bolt On": "£417",
    "OPTIONAL EQUIPMENT - 8 inch Hatch": "£185",
    "OPTIONAL EQUIPMENT - 12 inch Hatch": "£228",
    "OPTIONAL EQUIPMENT - 12 inch Hatch with Sock": "£310",
    "OPTIONAL EQUIPMENT - Spring Drawbar (Adjustable)": "Standard",
    "OPTIONAL EQUIPMENT - Swivel Hitch": "£195",
    "OPTIONAL EQUIPMENT - Hyd Door Safety Valve": "£215 / (DF-1.5)",
    "OPTIONAL EQUIPMENT - Hyd Door Seal": "£245",
    "OPTIONAL EQUIPMENT - Hyd Up & Over Grain Door": "Standard",
    "OPTIONAL EQUIPMENT - Hydraulic Door Attachment Style Silage Sides":
      "Standard - When Silage Sides Specified (DF-2)",
    "OPTIONAL EQUIPMENT - Swinging Door Style Silage Sides": "Optional (DF-3)",
    "OPTIONAL EQUIPMENT - Trailer Cover (640g PVC)": "£278 / (DF-0.25)",
    "OPTIONAL EQUIPMENT - Roll Over Cover (1000g PVC)": "£1,588 / (DF-5)",
    "OPTIONAL EQUIPMENT - Hydraulic Front to Back Cover": "£3,680",
    "OPTIONAL EQUIPMENT - LED Beacon": "£145 / (DF-0.25)",
    "OPTIONAL EQUIPMENT - LED Tail Lights": "Standard",
    "OPTIONAL EQUIPMENT - High Level LED Lights": "£292 / (DF-1.5)",
    "OPTIONAL EQUIPMENT - LED Worklights": "£380 / (DF-2)",
    "OPTIONAL EQUIPMENT - 10 Stud 406 x 120 Commercial Axle": "£1,364",
    "OPTIONAL EQUIPMENT - 10 Stud Commercial Axle c/w ABS & Air Brakes":
      "£4,620",
    "OPTIONAL EQUIPMENT - Rear Steering Axle": "N/A",
    "OPTIONAL EQUIPMENT - Air / Oil Brakes (Non ABS)c/w Load Sensing":
      "£1,517 (DF-4)",
    "OPTIONAL EQUIPMENT - Oil Load Sensing": "£850 (DF-2)",
    "OPTIONAL EQUIPMENT - Small Perpsex Front Window": "£165 / (DF-0.5)",
    "OPTIONAL EQUIPMENT - Large Perspex Front Window": "£740",
    "OPTIONAL EQUIPMENT - Rear Tow Hitch c/w Lights & Brakes": "£325 / (DF-2)",
  },
  // Model 4 (Basic Price £19,600)
  {
    "Basic Price": "£19,600",
    "Silage Price - Hyd Door Attach Style": "£21,869",
    "Silage Price - Swinging Door Style": "N/A",
    "Body Size - Imperial": "18' x 7' 6\" - 8' x 4'",
    "Standard Tyre Size": "385 - 65 x 22.5",
    Axle: "8 stud 80mm",
    Brake: "350 x 90",
    "Carrying Capacity": "12 tons",
    "Floor Thickness": "5mm",
    "Side Thickness": "4mm",
    "Lights & Hyd Brakes": "Standard",
    "Side Loading Panels": "Standard",
    "Volume Basic": "558 cu.ft / 15.8 cu.mtrs",
    "Volume Silage - Swinging Door Style Sides": "1116 cu.ft / 31.6 cu.mtrs",
    "Volume Silage - Hyd Door Attach. Style Sides": "999 cu.ft / 28.3 cu.mtrs",
    "Basic Trailer Weight": "4860 kgs",
    "Loading Height Basic": '96"/2.44m',
    "Tip Angle (Degrees)": "49",
    "Tipping Height Basic": "19' 8\"",
    "OPTIONAL EQUIPMENT - 400-60 x 15.5": "N/A",
    "OPTIONAL EQUIPMENT - 340 x 65 x 18 Radial": "N/A",
    "OPTIONAL EQUIPMENT - 550-45 x 22.5 c/w Mudguards": "£2,257",
    "OPTIONAL EQUIPMENT - 560-45 x 22.5 c/w Mudguards": "£2,947",
    "OPTIONAL EQUIPMENT - 560-60 x 22.5 c/w Mudguards": "N/A",
    "OPTIONAL EQUIPMENT - Mudguards / Wings - Bolt On": "£417",
    "OPTIONAL EQUIPMENT - 8 inch Hatch": "£185",
    "OPTIONAL EQUIPMENT - 12 inch Hatch": "£228",
    "OPTIONAL EQUIPMENT - 12 inch Hatch with Sock": "£310",
    "OPTIONAL EQUIPMENT - Spring Drawbar (Adjustable)": "Standard",
    "OPTIONAL EQUIPMENT - Swivel Hitch": "£195",
    "OPTIONAL EQUIPMENT - Hyd Door Safety Valve": "£215 / (DF-1.5)",
    "OPTIONAL EQUIPMENT - Hyd Door Seal": "£245",
    "OPTIONAL EQUIPMENT - Hyd Up & Over Grain Door": "Standard",
    "OPTIONAL EQUIPMENT - Hydraulic Door Attachment Style Silage Sides":
      "Standard - When Silage Sides Specified (DF-2)",
    "OPTIONAL EQUIPMENT - Swinging Door Style Silage Sides": "N/A",
    "OPTIONAL EQUIPMENT - Trailer Cover (640g PVC)": "£290 / (DF-0.25)",
    "OPTIONAL EQUIPMENT - Roll Over Cover (1000g PVC)": "£1,588 / (DF-5)",
    "OPTIONAL EQUIPMENT - Hydraulic Front to Back Cover": "£3,680",
    "OPTIONAL EQUIPMENT - LED Beacon": "£145 / (DF-0.25)",
    "OPTIONAL EQUIPMENT - LED Tail Lights": "Standard",
    "OPTIONAL EQUIPMENT - High Level LED Lights": "£292 / (DF-1.5)",
    "OPTIONAL EQUIPMENT - LED Worklights": "£380 / (DF-2)",
    "OPTIONAL EQUIPMENT - 10 Stud 406 x 120 Commercial Axle": "£1,364",
    "OPTIONAL EQUIPMENT - 10 Stud Commercial Axle c/w ABS & Air Brakes":
      "£4,620",
    "OPTIONAL EQUIPMENT - Rear Steering Axle": "N/A",
    "OPTIONAL EQUIPMENT - Air / Oil Brakes (Non ABS)c/w Load Sensing":
      "£1,517 (DF-4)",
    "OPTIONAL EQUIPMENT - Oil Load Sensing": "£850 (DF-2)",
    "OPTIONAL EQUIPMENT - Small Perpsex Front Window": "£165 / (DF-0.5)",
    "OPTIONAL EQUIPMENT - Large Perspex Front Window": "£740",
    "OPTIONAL EQUIPMENT - Rear Tow Hitch c/w Lights & Brakes": "£325 / (DF-2)",
  },
  // Model 5 (Basic Price £19,600 - Different Body Size)
  {
    "Basic Price": "£19,600",
    "Silage Price - Hyd Door Attach Style": "£21,869",
    "Silage Price - Swinging Door Style": "N/A",
    "Body Size - Imperial": "16' x 7' 6\" - 8' x 4' 8\"",
    "Standard Tyre Size": "385 - 65 x 22.5",
    Axle: "8 stud 80mm",
    Brake: "350 x 90",
    "Carrying Capacity": "12 tons",
    "Floor Thickness": "5mm",
    "Side Thickness": "4mm",
    "Lights & Hyd Brakes": "Standard",
    "Side Loading Panels": "Standard",
    "Volume Basic": "578 cu.ft / 16.3 cu.mtrs",
    "Volume Silage - Swinging Door Style Sides": "N/A",
    "Volume Silage - Hyd Door Attach. Style Sides": "971 cu.ft / 27.5 cu.mtrs",
    "Basic Trailer Weight": "4620 kgs",
    "Loading Height Basic": '104"/2.64m',
    "Tip Angle (Degrees)": "46",
    "Tipping Height Basic": "18' 2\"",
    "OPTIONAL EQUIPMENT - 400-60 x 15.5": "N/A",
    "OPTIONAL EQUIPMENT - 340 x 65 x 18 Radial": "N/A",
    "OPTIONAL EQUIPMENT - 550-45 x 22.5 c/w Mudguards": "£2,257",
    "OPTIONAL EQUIPMENT - 560-45 x 22.5 c/w Mudguards": "£2,947",
    "OPTIONAL EQUIPMENT - 560-60 x 22.5 c/w Mudguards": "N/A",
    "OPTIONAL EQUIPMENT - Mudguards / Wings - Bolt On": "£417",
    "OPTIONAL EQUIPMENT - 8 inch Hatch": "£185",
    "OPTIONAL EQUIPMENT - 12 inch Hatch": "£228",
    "OPTIONAL EQUIPMENT - 12 inch Hatch with Sock": "£310",
    "OPTIONAL EQUIPMENT - Spring Drawbar (Adjustable)": "Standard",
    "OPTIONAL EQUIPMENT - Swivel Hitch": "£195",
    "OPTIONAL EQUIPMENT - Hyd Door Safety Valve": "£215 / (DF-1.5)",
    "OPTIONAL EQUIPMENT - Hyd Door Seal": "Standard",
    "OPTIONAL EQUIPMENT - Hyd Up & Over Grain Door": "Standard",
    "OPTIONAL EQUIPMENT - Hydraulic Door Attachment Style Silage Sides":
      "Standard - When Silage Sides Specified (DF-2)",
    "OPTIONAL EQUIPMENT - Swinging Door Style Silage Sides": "N/A",
    "OPTIONAL EQUIPMENT - Trailer Cover (640g PVC)": "£290 / (DF-0.25)",
    "OPTIONAL EQUIPMENT - Roll Over Cover (1000g PVC)": "£1,588 / (DF-5)",
    "OPTIONAL EQUIPMENT - Hydraulic Front to Back Cover": "£3,680",
    "OPTIONAL EQUIPMENT - LED Beacon": "£145 / (DF-0.25)",
    "OPTIONAL EQUIPMENT - LED Tail Lights": "Standard",
    "OPTIONAL EQUIPMENT - High Level LED Lights": "£292 / (DF-1.5)",
    "OPTIONAL EQUIPMENT - LED Worklights": "£380 / (DF-2)",
    "OPTIONAL EQUIPMENT - 10 Stud 406 x 120 Commercial Axle": "£1,364",
    "OPTIONAL EQUIPMENT - 10 Stud Commercial Axle c/w ABS & Air Brakes":
      "£4,620",
    "OPTIONAL EQUIPMENT - Rear Steering Axle": "N/A",
    "OPTIONAL EQUIPMENT - Air / Oil Brakes (Non ABS)c/w Load Sensing":
      "£1,517 (DF-4)",
    "OPTIONAL EQUIPMENT - Oil Load Sensing": "£850 (DF-2)",
    "OPTIONAL EQUIPMENT - Small Perpsex Front Window": "£165 / (DF-0.5)",
    "OPTIONAL EQUIPMENT - Large Perspex Front Window": "£740",
    "OPTIONAL EQUIPMENT - Rear Tow Hitch c/w Lights & Brakes": "£325 / (DF-2)",
  },
  // Model 6 (Basic Price £22,995)
  {
    "Basic Price": "£22,995",
    "Silage Price - Hyd Door Attach Style": "£25,983",
    "Silage Price - Swinging Door Style": "N/A",
    "Body Size - Imperial": "21' x 7' 6\" - 8' x 4'",
    "Standard Tyre Size": "385 - 65 x 22.5",
    Axle: "10 stud 120mm High Speed Commercial",
    Brake: "420 x 180 S Cam",
    "Carrying Capacity": "14.5 tons",
    "Floor Thickness": "5mm",
    "Side Thickness": "4mm",
    "Lights & Hyd Brakes": "Standard",
    "Side Loading Panels": "Standard",
    "Volume Basic": "651 cu.ft / 18.4 cu.mtrs",
    "Volume Silage - Swinging Door Style Sides": "1302 cu.ft / 36.8 cu.mtrs",
    "Volume Silage - Hyd Door Attach. Style Sides": "1166 cu.ft / 33 cu.mtrs",
    "Basic Trailer Weight": "5700 kgs",
    "Loading Height Basic": '96"/2.44m',
    "Tip Angle (Degrees)": "50",
    "Tipping Height Basic": "22' 7\"",
    "OPTIONAL EQUIPMENT - 400-60 x 15.5": "N/A",
    "OPTIONAL EQUIPMENT - 340 x 65 x 18 Radial": "N/A",
    "OPTIONAL EQUIPMENT - 550-45 x 22.5 c/w Mudguards": "£1840 / (DF-1)",
    "OPTIONAL EQUIPMENT - 560-45 x 22.5 c/w Mudguards": "£2530 / (DF-1)",
    "OPTIONAL EQUIPMENT - 560-60 x 22.5 c/w Mudguards": "£3,180 / (DF-1)",
    "OPTIONAL EQUIPMENT - Mudguards / Wings - Bolt On": "Standard",
    "OPTIONAL EQUIPMENT - 8 inch Hatch": "£185",
    "OPTIONAL EQUIPMENT - 12 inch Hatch": "£228",
    "OPTIONAL EQUIPMENT - 12 inch Hatch with Sock": "£310",
    "OPTIONAL EQUIPMENT - Spring Drawbar (Adjustable)": "Standard",
    "OPTIONAL EQUIPMENT - Swivel Hitch": "£195",
    "OPTIONAL EQUIPMENT - Hyd Door Safety Valve": "£215 / (DF-1.5)",
    "OPTIONAL EQUIPMENT - Hyd Door Seal": "£245",
    "OPTIONAL EQUIPMENT - Hyd Up & Over Grain Door": "Standard",
    "OPTIONAL EQUIPMENT - Hydraulic Door Attachment Style Silage Sides":
      "Standard - When Silage Sides Specified (DF-2)",
    "OPTIONAL EQUIPMENT - Swinging Door Style Silage Sides": "N/A",
    "OPTIONAL EQUIPMENT - Trailer Cover (640g PVC)": "£314 / (DF-0.25)",
    "OPTIONAL EQUIPMENT - Roll Over Cover (1000g PVC)": "£1,588 / (DF-5)",
    "OPTIONAL EQUIPMENT - Hydraulic Front to Back Cover": "£3,680",
    "OPTIONAL EQUIPMENT - LED Beacon": "Standard",
    "OPTIONAL EQUIPMENT - LED Tail Lights": "Standard",
    "OPTIONAL EQUIPMENT - High Level LED Lights": "£292 / (DF-1.5)",
    "OPTIONAL EQUIPMENT - LED Worklights": "£380 / (DF-2)",
    "OPTIONAL EQUIPMENT - 10 Stud 406 x 120 Commercial Axle": "N/A",
    "OPTIONAL EQUIPMENT - 10 Stud Commercial Axle c/w ABS & Air Brakes":
      "£3108 / (DF-6)",
    "OPTIONAL EQUIPMENT - Rear Steering Axle": "£4,350",
    "OPTIONAL EQUIPMENT - Air / Oil Brakes (Non ABS)c/w Load Sensing":
      "£1,517 (DF-4)",
    "OPTIONAL EQUIPMENT - Oil Load Sensing": "£850 (DF-2)",
    "OPTIONAL EQUIPMENT - Small Perpsex Front Window": "£165 / (DF-0.5)",
    "OPTIONAL EQUIPMENT - Large Perspex Front Window": "£740",
    "OPTIONAL EQUIPMENT - Rear Tow Hitch c/w Lights & Brakes": "£325 / (DF-2)",
  },
  // Model 7 (Basic Price £22,995 - Different Body Size)
  {
    "Basic Price": "£22,995",
    "Silage Price - Hyd Door Attach Style": "£25,983",
    "Silage Price - Swinging Door Style": "N/A",
    "Body Size - Imperial": "18' x 7' 6\" - 8' x 4' 8\"",
    "Standard Tyre Size": "385 - 65 x 22.5",
    Axle: "10 stud 120mm High Speed Commercial",
    Brake: "420 x 180 S Cam",
    "Carrying Capacity": "14.5 tons",
    "Floor Thickness": "5mm",
    "Side Thickness": "4mm",
    "Lights & Hyd Brakes": "Standard",
    "Side Loading Panels": "Standard",
    "Volume Basic": "651 cu.ft / 18.4 cu.mtrs",
    "Volume Silage - Swinging Door Style Sides": "N/A",
    "Volume Silage - Hyd Door Attach. Style Sides": "1092 cu.ft / 31 cu.mtrs",
    "Basic Trailer Weight": "5700 kgs",
    "Loading Height Basic": '104"/2.64m',
    "Tip Angle (Degrees)": "50",
    "Tipping Height Basic": "20' 2\"",
    "OPTIONAL EQUIPMENT - 400-60 x 15.5": "N/A",
    "OPTIONAL EQUIPMENT - 340 x 65 x 18 Radial": "N/A",
    "OPTIONAL EQUIPMENT - 550-45 x 22.5 c/w Mudguards": "£1840 / (DF-1)",
    "OPTIONAL EQUIPMENT - 560-45 x 22.5 c/w Mudguards": "£2530 / (DF-1)",
    "OPTIONAL EQUIPMENT - 560-60 x 22.5 c/w Mudguards": "£3,180 / (DF-1)",
    "OPTIONAL EQUIPMENT - Mudguards / Wings - Bolt On": "Standard",
    "OPTIONAL EQUIPMENT - 8 inch Hatch": "£185",
    "OPTIONAL EQUIPMENT - 12 inch Hatch": "£228",
    "OPTIONAL EQUIPMENT - 12 inch Hatch with Sock": "£310",
    "OPTIONAL EQUIPMENT - Spring Drawbar (Adjustable)": "Standard",
    "OPTIONAL EQUIPMENT - Swivel Hitch": "£195",
    "OPTIONAL EQUIPMENT - Hyd Door Safety Valve": "£215 / (DF-1.5)",
    "OPTIONAL EQUIPMENT - Hyd Door Seal": "Standard",
    "OPTIONAL EQUIPMENT - Hyd Up & Over Grain Door": "Standard",
    "OPTIONAL EQUIPMENT - Hydraulic Door Attachment Style Silage Sides":
      "Standard - When Silage Sides Specified (DF-2)",
    "OPTIONAL EQUIPMENT - Swinging Door Style Silage Sides": "N/A",
    "OPTIONAL EQUIPMENT - Trailer Cover (640g PVC)": "£290 / (DF-0.25)",
    "OPTIONAL EQUIPMENT - Roll Over Cover (1000g PVC)": "£1,588 / (DF-5)",
    "OPTIONAL EQUIPMENT - Hydraulic Front to Back Cover": "£3,680",
    "OPTIONAL EQUIPMENT - LED Beacon": "Standard",
    "OPTIONAL EQUIPMENT - LED Tail Lights": "Standard",
    "OPTIONAL EQUIPMENT - High Level LED Lights": "£292 / (DF-1.5)",
    "OPTIONAL EQUIPMENT - LED Worklights": "£380 / (DF-2)",
    "OPTIONAL EQUIPMENT - 10 Stud 406 x 120 Commercial Axle": "N/A",
    "OPTIONAL EQUIPMENT - 10 Stud Commercial Axle c/w ABS & Air Brakes":
      "£3108 / (DF-6)",
    "OPTIONAL EQUIPMENT - Rear Steering Axle": "£4,350",
    "OPTIONAL EQUIPMENT - Air / Oil Brakes (Non ABS)c/w Load Sensing":
      "£1,517 (DF-4)",
    "OPTIONAL EQUIPMENT - Oil Load Sensing": "£850 (DF-2)",
    "OPTIONAL EQUIPMENT - Small Perpsex Front Window": "£165 / (DF-0.5)",
    "OPTIONAL EQUIPMENT - Large Perspex Front Window": "£740",
    "OPTIONAL EQUIPMENT - Rear Tow Hitch c/w Lights & Brakes": "£325 / (DF-2)",
  },
  // Model 8 (Basic Price £24,500)
  {
    "Basic Price": "£24,500",
    "Silage Price - Hyd Door Attach Style": "£27,870",
    "Silage Price - Swinging Door Style": "N/A",
    "Body Size - Imperial": "24' x 7' 6\" - 8' x 4'",
    "Standard Tyre Size": "385 - 65 x 22.5",
    Axle: "10 stud 120mm High Speed Commercial",
    Brake: "420 x 180 S Cam",
    "Carrying Capacity": "16.5 tons",
    "Floor Thickness": "5mm",
    "Side Thickness": "4mm",
    "Lights & Hyd Brakes": "Standard",
    "Side Loading Panels": "Standard",
    "Volume Basic": "744 cu.ft / 21.1 cu.mtrs",
    "Volume Silage - Swinging Door Style Sides": "1488 cu.ft / 42.1 cu.mtrs",
    "Volume Silage - Hyd Door Attach. Style Sides": "1335 cu.ft / 37.7 cu.mtrs",
    "Basic Trailer Weight": "6380 kgs",
    "Loading Height Basic": '98"/2.49m',
    "Tip Angle (Degrees)": "51",
    "Tipping Height Basic": "23' 11\"",
    "OPTIONAL EQUIPMENT - 400-60 x 15.5": "N/A",
    "OPTIONAL EQUIPMENT - 340 x 65 x 18 Radial": "N/A",
    "OPTIONAL EQUIPMENT - 550-45 x 22.5 c/w Mudguards": "N/A",
    "OPTIONAL EQUIPMENT - 560-45 x 22.5 c/w Mudguards": "£2530 / (DF-1)",
    "OPTIONAL EQUIPMENT - 560-60 x 22.5 c/w Mudguards": "£3,180 / (DF-1)",
    "OPTIONAL EQUIPMENT - Mudguards / Wings - Bolt On": "Standard",
    "OPTIONAL EQUIPMENT - 8 inch Hatch": "£185",
    "OPTIONAL EQUIPMENT - 12 inch Hatch": "£228",
    "OPTIONAL EQUIPMENT - 12 inch Hatch with Sock": "£310",
    "OPTIONAL EQUIPMENT - Spring Drawbar (Adjustable)": "Standard",
    "OPTIONAL EQUIPMENT - Swivel Hitch": "£195",
    "OPTIONAL EQUIPMENT - Hyd Door Safety Valve": "£215 / (DF-1.5)",
    "OPTIONAL EQUIPMENT - Hyd Door Seal": "£245",
    "OPTIONAL EQUIPMENT - Hyd Up & Over Grain Door": "Standard",
    "OPTIONAL EQUIPMENT - Hydraulic Door Attachment Style Silage Sides":
      "Standard - When Silage Sides Specified (DF-2)",
    "OPTIONAL EQUIPMENT - Swinging Door Style Silage Sides": "N/A",
    "OPTIONAL EQUIPMENT - Trailer Cover (640g PVC)": "£338 / (DF-0.25)",
    "OPTIONAL EQUIPMENT - Roll Over Cover (1000g PVC)": "£1,588 / (DF-5)",
    "OPTIONAL EQUIPMENT - Hydraulic Front to Back Cover": "£3,680",
    "OPTIONAL EQUIPMENT - LED Beacon": "Standard",
    "OPTIONAL EQUIPMENT - LED Tail Lights": "Standard",
    "OPTIONAL EQUIPMENT - High Level LED Lights": "£292 / (DF-1.5)",
    "OPTIONAL EQUIPMENT - LED Worklights": "£380 / (DF-2)",
    "OPTIONAL EQUIPMENT - 10 Stud 406 x 120 Commercial Axle": "N/A",
    "OPTIONAL EQUIPMENT - 10 Stud Commercial Axle c/w ABS & Air Brakes":
      "£3108 / (DF-6)",
    "OPTIONAL EQUIPMENT - Rear Steering Axle": "£4,350",
    "OPTIONAL EQUIPMENT - Air / Oil Brakes (Non ABS)c/w Load Sensing":
      "£1,517 (DF-4)",
    "OPTIONAL EQUIPMENT - Oil Load Sensing": "£850 (DF-2)",
    "OPTIONAL EQUIPMENT - Small Perpsex Front Window": "£165 / (DF-0.5)",
    "OPTIONAL EQUIPMENT - Large Perspex Front Window": "£740",
    "OPTIONAL EQUIPMENT - Rear Tow Hitch c/w Lights & Brakes": "£325 / (DF-2)",
  },
  // Model 9 (Basic Price £24,500 - Different Body Size)
  {
    "Basic Price": "£24,500",
    "Silage Price - Hyd Door Attach Style": "£27,870",
    "Silage Price - Swinging Door Style": "N/A",
    "Body Size - Imperial": "21' x 7' 6\" - 8' x 4' 8\"",
    "Standard Tyre Size": "385 - 65 x 22.5",
    Axle: "10 stud 120mm High Speed Commercial",
    Brake: "420 x 180 S Cam",
    "Carrying Capacity": "16.5 tons",
    "Floor Thickness": "5mm",
    "Side Thickness": "4mm",
    "Lights & Hyd Brakes": "Standard",
    "Side Loading Panels": "Standard",
    "Volume Basic": "759 cu.ft / 21.5 cu.mtrs",
    "Volume Silage - Swinging Door Style Sides": "N/A",
    "Volume Silage - Hyd Door Attach. Style Sides": "1274 cu.ft / 36.1 cu.mtrs",
    "Basic Trailer Weight": "6380 kgs",
    "Loading Height Basic": '106"/2.69m',
    "Tip Angle (Degrees)": "51",
    "Tipping Height Basic": "23' 1\"",
    "OPTIONAL EQUIPMENT - 400-60 x 15.5": "N/A",
    "OPTIONAL EQUIPMENT - 340 x 65 x 18 Radial": "N/A",
    "OPTIONAL EQUIPMENT - 550-45 x 22.5 c/w Mudguards": "N/A",
    "OPTIONAL EQUIPMENT - 560-45 x 22.5 c/w Mudguards": "£2530 / (DF-1)",
    "OPTIONAL EQUIPMENT - 560-60 x 22.5 c/w Mudguards": "£3,180 / (DF-1)",
    "OPTIONAL EQUIPMENT - Mudguards / Wings - Bolt On": "Standard",
    "OPTIONAL EQUIPMENT - 8 inch Hatch": "£185",
    "OPTIONAL EQUIPMENT - 12 inch Hatch": "£228",
    "OPTIONAL EQUIPMENT - 12 inch Hatch with Sock": "£310",
    "OPTIONAL EQUIPMENT - Spring Drawbar (Adjustable)": "Standard",
    "OPTIONAL EQUIPMENT - Swivel Hitch": "£195",
    "OPTIONAL EQUIPMENT - Hyd Door Safety Valve": "£215 / (DF-1.5)",
    "OPTIONAL EQUIPMENT - Hyd Door Seal": "Standard",
    "OPTIONAL EQUIPMENT - Hyd Up & Over Grain Door": "Standard",
    "OPTIONAL EQUIPMENT - Hydraulic Door Attachment Style Silage Sides":
      "Standard - When Silage Sides Specified (DF-2)",
    "OPTIONAL EQUIPMENT - Swinging Door Style Silage Sides": "N/A",
    "OPTIONAL EQUIPMENT - Trailer Cover (640g PVC)": "£314 / (DF-0.25)",
    "OPTIONAL EQUIPMENT - Roll Over Cover (1000g PVC)": "£1,588 / (DF-5)",
    "OPTIONAL EQUIPMENT - Hydraulic Front to Back Cover": "£3,680",
    "OPTIONAL EQUIPMENT - LED Beacon": "Standard",
    "OPTIONAL EQUIPMENT - LED Tail Lights": "Standard",
    "OPTIONAL EQUIPMENT - High Level LED Lights": "£292 / (DF-1.5)",
    "OPTIONAL EQUIPMENT - LED Worklights": "£380 / (DF-2)",
    "OPTIONAL EQUIPMENT - 10 Stud 406 x 120 Commercial Axle": "N/A",
    "OPTIONAL EQUIPMENT - 10 Stud Commercial Axle c/w ABS & Air Brakes":
      "£3108 / (DF-6)",
    "OPTIONAL EQUIPMENT - Rear Steering Axle": "£4,350",
    "OPTIONAL EQUIPMENT - Air / Oil Brakes (Non ABS)c/w Load Sensing":
      "£1,517 (DF-4)",
    "OPTIONAL EQUIPMENT - Oil Load Sensing": "£850 (DF-2)",
    "OPTIONAL EQUIPMENT - Small Perpsex Front Window": "£165 / (DF-0.5)",
    "OPTIONAL EQUIPMENT - Large Perspex Front Window": "£740",
    "OPTIONAL EQUIPMENT - Rear Tow Hitch c/w Lights & Brakes": "£325 / (DF-2)",
  },
  // Model 10 (Basic Price £26,000)
  {
    "Basic Price": "£26,000",
    "Silage Price - Hyd Door Attach Style": "£29,626",
    "Silage Price - Swinging Door Style": "N/A",
    "Body Size - Imperial": "24' x 7' 6\" - 8' x 4' 8\"",
    "Standard Tyre Size": "NEW 385-65 x 22.5",
    Axle: "10 stud 120mm High Speed Commercial",
    Brake: "420 x 180 S Cam",
    "Carrying Capacity": "18.5 tons",
    "Floor Thickness": "5mm",
    "Side Thickness": "4mm",
    "Lights & Hyd Brakes": "Standard",
    "Side Loading Panels": "Standard",
    "Volume Basic": "868 cu.ft / 24.5 cu.mtrs",
    "Volume Silage - Swinging Door Style Sides": "N/A",
    "Volume Silage - Hyd Door Attach. Style Sides": "1457 cu.ft / 41.2 cu.mtrs",
    "Basic Trailer Weight": "6,980 kgs",
    "Loading Height Basic": '106"/2.69m',
    "Tip Angle (Degrees)": "51",
    "Tipping Height Basic": "24' 5\"",
    "OPTIONAL EQUIPMENT - 400-60 x 15.5": "N/A",
    "OPTIONAL EQUIPMENT - 340 x 65 x 18 Radial": "N/A",
    "OPTIONAL EQUIPMENT - 550-45 x 22.5 c/w Mudguards": "N/A",
    "OPTIONAL EQUIPMENT - 560-45 x 22.5 c/w Mudguards": "N/A",
    "OPTIONAL EQUIPMENT - 560-60 x 22.5 c/w Mudguards": "£3,180 / (DF-1)",
    "OPTIONAL EQUIPMENT - Mudguards / Wings - Bolt On": "Standard",
    "OPTIONAL EQUIPMENT - 8 inch Hatch": "£185",
    "OPTIONAL EQUIPMENT - 12 inch Hatch": "£228",
    "OPTIONAL EQUIPMENT - 12 inch Hatch with Sock": "£310",
    "OPTIONAL EQUIPMENT - Spring Drawbar (Adjustable)": "Standard",
    "OPTIONAL EQUIPMENT - Swivel Hitch": "£195",
    "OPTIONAL EQUIPMENT - Hyd Door Safety Valve": "£215 / (DF-1.5)",
    "OPTIONAL EQUIPMENT - Hyd Door Seal": "Standard",
    "OPTIONAL EQUIPMENT - Hyd Up & Over Grain Door": "Standard",
    "OPTIONAL EQUIPMENT - Hydraulic Door Attachment Style Silage Sides":
      "Standard - When Silage Sides Specified (DF-2)",
    "OPTIONAL EQUIPMENT - Swinging Door Style Silage Sides": "N/A",
    "OPTIONAL EQUIPMENT - Trailer Cover (640g PVC)": "£338 / (DF-0.25)",
    "OPTIONAL EQUIPMENT - Roll Over Cover (1000g PVC)": "£1,588 / (DF-5)",
    "OPTIONAL EQUIPMENT - Hydraulic Front to Back Cover": "£3,680",
    "OPTIONAL EQUIPMENT - LED Beacon": "Standard",
    "OPTIONAL EQUIPMENT - LED Tail Lights": "Standard",
    "OPTIONAL EQUIPMENT - High Level LED Lights": "£292 / (DF-1.5)",
    "OPTIONAL EQUIPMENT - LED Worklights": "£380 / (DF-2)",
    "OPTIONAL EQUIPMENT - 10 Stud 406 x 120 Commercial Axle": "N/A",
    "OPTIONAL EQUIPMENT - 10 Stud Commercial Axle c/w ABS & Air Brakes":
      "£3108 / (DF-6)",
    "OPTIONAL EQUIPMENT - Rear Steering Axle": "£4,350",
    "OPTIONAL EQUIPMENT - Air / Oil Brakes (Non ABS)c/w Load Sensing":
      "£1,517 (DF-4)",
    "OPTIONAL EQUIPMENT - Oil Load Sensing": "£850 (DF-2)",
    "OPTIONAL EQUIPMENT - Small Perpsex Front Window": "£165 / (DF-0.5)",
    "OPTIONAL EQUIPMENT - Large Perspex Front Window": "£740",
    "OPTIONAL EQUIPMENT - Rear Tow Hitch c/w Lights & Brakes": "£325 / (DF-2)",
  },
];

window.FULL_PRODUCT_DATA = fullProductData;
